# Generated by Django 5.0.6 on 2024-06-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_manager_guardofficeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackManager',
            new_name='FeedbackGOUser',
        ),
        migrations.RenameModel(
            old_name='FeedbackEmployee',
            new_name='FeedbackGuard',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Guard',
        ),
        migrations.RenameModel(
            old_name='Division',
            new_name='GuardOffice',
        ),
        migrations.RenameModel(
            old_name='EmployeeSalary',
            new_name='GuardSalary',
        ),
        migrations.RenameModel(
            old_name='LeaveReportManager',
            new_name='LeaveReportGOUser',
        ),
        migrations.RenameModel(
            old_name='LeaveReportEmployee',
            new_name='LeaveReportGuard',
        ),
        migrations.RenameModel(
            old_name='NotificationManager',
            new_name='NotificationGOUser',
        ),
        migrations.RenameModel(
            old_name='NotificationEmployee',
            new_name='NotificationGuard',
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Site',
        ),
    ]
