# Generated by Django 5.0.6 on 2024-06-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_feedbackmanager_feedbackgouser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guard',
            old_name='division',
            new_name='guard_office',
        ),
        migrations.RenameField(
            model_name='guardofficeuser',
            old_name='division',
            new_name='guard_office',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='division',
            new_name='guard_office',
        ),
    ]
