# Generated by Django 5.0.6 on 2024-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_manager_feedbackgouser_guardofficeuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='employee',
            new_name='guard',
        ),
        migrations.RenameField(
            model_name='feedbackguard',
            old_name='employee',
            new_name='guard',
        ),
        migrations.RenameField(
            model_name='guardsalary',
            old_name='employee',
            new_name='guard',
        ),
        migrations.RenameField(
            model_name='leavereportguard',
            old_name='employee',
            new_name='guard',
        ),
        migrations.RenameField(
            model_name='notificationguard',
            old_name='employee',
            new_name='guard',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'CEO'), (2, 'GuardOfficeUser'), (3, 'Guard')], default=1, max_length=1),
        ),
    ]
