# Generated by Django 5.0.6 on 2024-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_employee_attendancereport_guard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportgouser',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leavereportguard',
            name='date',
            field=models.DateField(),
        ),
    ]
