# Generated by Django 5.0.6 on 2024-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_leavereportgouser_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportguard',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default=0),
        ),
    ]
