# Generated by Django 5.0.6 on 2024-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'CEO'), (2, 'GuardOfficeUser'), (3, 'Guard'), (4, 'Client')], default=1, max_length=1),
        ),
    ]
