# Generated by Django 5.0.6 on 2024-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
