# Generated by Django 5.0.6 on 2024-06-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_department_attendance_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.site'),
        ),
    ]
