# Generated by Django 5.0.6 on 2024-06-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_notificationgouser_is_read_notificationguard_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.site'),
        ),
    ]
