# Generated by Django 5.0.6 on 2024-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_client_site'),
    ]

    operations = [
    ]
