# Generated by Django 5.0.6 on 2024-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20240612_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='individual_leave_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardoffice',
            name='total_leave_days',
            field=models.IntegerField(default=25),
        ),
    ]
