# Generated by Django 5.0.6 on 2024-06-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_guard_average_rating_guard_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guardreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guardreview',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='guardreview',
            unique_together={('guard', 'client')},
        ),
    ]
