# Generated by Django 5.0.6 on 2024-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
