# Generated by Django 5.0.6 on 2024-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_guard_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='is_checked_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guardlocation',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardlocation',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
