# Generated by Django 5.0.6 on 2024-07-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_guard_is_checked_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='radius',
            field=models.IntegerField(default=50),
        ),
    ]
