# Generated by Django 5.0.6 on 2024-07-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_site_radius'),
    ]

    operations = [
    
    ]
