# Generated by Django 5.0.6 on 2024-07-03 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_feedbackclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
