# Generated by Django 5.0.6 on 2024-07-03 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_attendance_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
